CREATE TABLE SERVER_HOST(
  SERVER_NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (SERVER_NAME)
);

CREATE TABLE IP_ADDRESS(
  IP_ADDRESS INT NOT NULL,
  STATE VARCHAR(255) NOT NULL,
  SERVER_NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (IP_ADDRESS),
  FOREIGN KEY (SERVER_NAME) REFERENCES SERVER_HOST(SERVER_NAME)
);

CREATE TABLE USERS(
  USERNAME VARCHAR(30) NOT NULL,
  PASSWORD VARCHAR(30) NOT NULL,
  USER_TYPE VARCHAR(30) NOT NULL,
  SERVER_NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (USERNAME),
  FOREIGN KEY (SERVER_NAME) REFERENCES SERVER_HOST(SERVER_NAME)
);

CREATE TABLE APPLICATION(
  APPLICATION_ID INT NOT NULL,
  APPLICATION_NAME VARCHAR(255) NOT NULL,
  APPLICATION_TYPE VARCHAR(255) NOT NULL,
  PRIMARY KEY (APPLICATION_ID)
);

CREATE TABLE BINDING(
  BINDING_ID INT NOT NULL,
  APPLICATION_ID INT NOT NULL,
  SERVER_NAME VARCHAR(255) NOT NULL,
  IP_ADDRESS INT NOT NULL,
  PRIMARY KEY (BINDING_ID),
  FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATION(APPLICATION_ID),
  FOREIGN KEY (SERVER_NAME) REFERENCES SERVER_HOST(SERVER_NAME),
  FOREIGN KEY (IP_ADDRESS) REFERENCES IP_ADDRESS(IP_ADDRESS)
);