CREATE TABLE SERVER_HOST(
  SERVER_ID BIGINT(19) NOT NULL AUTO_INCREMENT,
  SERVER_NAME VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (SERVER_ID)
);

CREATE TABLE IP_ADDRESS(
  IP_ADDRESS VARCHAR(255) NOT NULL,
  STATE VARCHAR(255) NOT NULL,
  SERVER_ID BIGINT(19) NOT NULL,
  PRIMARY KEY (IP_ADDRESS),
  FOREIGN KEY (SERVER_ID) REFERENCES SERVER_HOST(SERVER_ID)
);

CREATE TABLE USER(
  USER_ID BIGINT(19) NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(30) NOT NULL UNIQUE,
  PASSWORD VARCHAR(30) NOT NULL,
  USER_TYPE VARCHAR(30) NOT NULL,
  SERVER_ID BIGINT(19) NOT NULL,
  PRIMARY KEY (USER_ID),
  FOREIGN KEY (SERVER_ID) REFERENCES SERVER_HOST(SERVER_ID)
);

CREATE TABLE APPLICATION(
  APPLICATION_ID BIGINT(19) NOT NULL AUTO_INCREMENT,
  APPLICATION_NAME VARCHAR(255) NOT NULL UNIQUE,
  APPLICATION_TYPE VARCHAR(255) NOT NULL,
  APPLICATION_USER BIGINT(19) NOT NULL,
  PRIMARY KEY (APPLICATION_ID),
  FOREIGN KEY (APPLICATION_USER) REFERENCES USER(USER_ID)
);

CREATE TABLE BINDING(
  BINDING_ID BIGINT(19) NOT NULL AUTO_INCREMENT,
  APPLICATION_ID BIGINT(19) NOT NULL,
  SERVER_ID BIGINT(19) NOT NULL,
  IP_ADDRESS VARCHAR(255) NOT NULL,
  PRIMARY KEY (BINDING_ID),
  FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATION(APPLICATION_ID),
  FOREIGN KEY (SERVER_ID) REFERENCES SERVER_HOST(SERVER_ID),
  FOREIGN KEY (IP_ADDRESS) REFERENCES IP_ADDRESS(IP_ADDRESS)
);